language: cpp
compiler: g++
dist: trusty

install:
 - export CXX="g++-7"
 - ./autogen.sh

before_install:
 - sudo add-apt-repository -y ppa:team-xbmc/ppa
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-7
 - sudo apt-get install -qq libegl1-mesa-dev
 - sudo apt-get install -y libsdl2-dev
 - sudo apt-get install -qq doxygen
 - sudo apt-get install -qq ncompress
 - sudo apt-get install -qq libgtkmm-3.0-dev
 - sudo apt-get install -qq libxml++2.6-dev
 - sudo apt-get install -qq libsdl2-image-dev
 - sudo apt-get install -qq libsdl2-mixer-dev
 - sudo apt-get install -y libboost-all-dev
 - sudo apt-get install -qq lua5.1
 - sudo apt-get install -qq liblua5.1-0-dev
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
 
script: make
