language: cpp
compiler: g++
dist: trusty

install:
 - export CXX="g++-7"
 - wget ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng16/libpng-1.6.34.tar.gz && tar xzf libpng-1.6.34.tar.gz && pushd libpng-1.6.34 && ./configure --prefix=/usr && make && sudo make install && popd;
 - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz && tar -xzvf SDL2-2.0.7.tar.gz && pushd SDL2-2.0.7 && ./configure --prefix=/usr && make && sudo make install && popd;
 - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.2.tar.gz && tar -xzvf SDL2_mixer-2.0.2.tar.gz && pushd SDL2_mixer-2.0.2 && ./configure --prefix=/usr && make && sudo make install && popd;
 - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.2.tar.gz && tar -xzvf SDL2_image-2.0.2.tar.gz && pushd SDL2_image-2.0.2 && ./configure --prefix=/usr && make && sudo make install && popd;

before_install:
 - sudo add-apt-repository -y ppa:team-xbmc/ppa
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots 
 - sudo apt-get update  -qq
 - sudo apt-get remove  -y libpng-dev libpng
 - sudo apt-get install -qq libegl1-mesa-dev
 - sudo apt-get install -qq doxygen
 - sudo apt-get install -qq ncompress
 - sudo apt-get install -qq libgtkmm-3.0-dev
 - sudo apt-get install -qq libxml++2.6-dev
 - sudo apt-get install -y  libboost-all-dev
 - sudo apt-get install -qq lua5.1
 - sudo apt-get install -qq liblua5.1-0-dev
 - sudo apt-get install -qq libpng-dev
 - sudo apt-get install -qq g++-7
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

before_script:
 - ./autogen.sh

script: make
