language: C

install:
 - ./autogen.sh

before_install:
 - sudo add-apt-repository -y ppa:team-xbmc/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq libegl1-mesa-dev
 - sudo apt-get install -y libsdl2-dev
 - sudo apt-get install -qq doxygen
 - sudo apt-get install -qq ncompress
 - sudo apt-get install -qq libgtkmm-3.0-dev
 - sudo apt-get install -qq libxml++2.6-dev
 - sudo apt-get install -qq libsdl2-image-dev
 - sudo apt-get install -qq libsdl2-mixer-dev
 - sudo apt install -y libboost-all-dev

script: make
